name: Java CI with Maven and Gauge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Gauge
      run: |
        curl -SsL https://downloads.gauge.org/stable | sh
        gauge --version

    - name: Install Gauge plugins
      run: |
        gauge install java
        gauge install html-report
        gauge install screenshot
        gauge install spectacle
        gauge install xml-report

    - name: Build and Test with Maven
      run: mvn -B test -DfailIfNoTests=false
      env:
        BROWSER: chrome
        HEADLESS: true

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: reports/